import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Static pages
      { source: '/about.html', destination: '/about', permanent: true },
      { source: '/contact.html', destination: '/contact', permanent: true },
      { source: '/gallery.html', destination: '/gallery', permanent: true },

      // Service pages (old .html → new /services/[slug])
      { source: '/genral-pest-control.html', destination: '/services/general-pest-control', permanent: true },
      { source: '/spider-control.html', destination: '/services/spider-control', permanent: true },
      { source: '/termite-control.html', destination: '/services/termite-control', permanent: true },
      { source: '/rodent-control.html', destination: '/services/rodent-control', permanent: true },
      { source: '/wood-borer-control.html', destination: '/services/wood-borer-control', permanent: true },
      { source: '/honey-bee-control.html', destination: '/services/honey-bee-control', permanent: true },
      { source: '/bed-bugs-control.html', destination: '/services/bed-bugs-control', permanent: true },
      { source: '/bird-nesting-control.html', destination: '/services/bird-nesting-control', permanent: true },
      { source: '/mosquito-control.html', destination: '/services/mosquito-control', permanent: true },
      { source: '/rats-control.html', destination: '/services/rats-control', permanent: true },
      { source: '/cockroaches-control.html', destination: '/services/cockroach-control', permanent: true },
      { source: '/weed-control.html', destination: '/services/weed-control', permanent: true },
      { source: '/ants-control.html', destination: '/services/ants-control', permanent: true },
      { source: '/sanitization.html', destination: '/services/sanitization', permanent: true },
      { source: '/fly-control.html', destination: '/services/fly-control', permanent: true },

      // Location pages (old pest-control-service-*.html → new /locations/*)
      { source: '/pest-control-service-airoli.html', destination: '/locations/airoli', permanent: true },
      { source: '/pest-control-service-akola.html', destination: '/locations/akola', permanent: true },
      { source: '/pest-control-service-ambernath.html', destination: '/locations/ambernath', permanent: true },
      { source: '/pest-control-service-ambivali.html', destination: '/locations/ambivali', permanent: true },
      { source: '/pest-control-service-andheri-midc.html', destination: '/locations/andheri-midc', permanent: true },
      { source: '/pest-control-service-andheri-seepz.html', destination: '/locations/andheri-seepz', permanent: true },
      { source: '/pest-control-service-andheri.html', destination: '/locations/andheri', permanent: true },
      { source: '/pest-control-service-asalpha.html', destination: '/locations/asalpha', permanent: true },
      { source: '/pest-control-service-asangaon.html', destination: '/locations/asangaon', permanent: true },
      { source: '/pest-control-service-bandra.html', destination: '/locations/bandra', permanent: true },
      { source: '/pest-control-service-bhandup.html', destination: '/locations/bhandup', permanent: true },
      { source: '/pest-control-service-bhayandar.html', destination: '/locations/bhayandar', permanent: true },
      { source: '/pest-control-service-bhayander.html', destination: '/locations/bhayander', permanent: true },
      { source: '/pest-control-service-bhiwandi.html', destination: '/locations/bhiwandi', permanent: true },
      { source: '/pest-control-service-boisar.html', destination: '/locations/boisar', permanent: true },
      { source: '/pest-control-service-borivali.html', destination: '/locations/borivali', permanent: true },
      { source: '/pest-control-service-byculla.html', destination: '/locations/byculla', permanent: true },
      { source: '/pest-control-service-charni-road.html', destination: '/locations/charni-road', permanent: true },
      { source: '/pest-control-service-chembur.html', destination: '/locations/chembur', permanent: true },
      { source: '/pest-control-service-churchgate.html', destination: '/locations/churchgate', permanent: true },
      { source: '/pest-control-service-cst.html', destination: '/locations/cst', permanent: true },
      { source: '/pest-control-service-dadar.html', destination: '/locations/dadar', permanent: true },
      { source: '/pest-control-service-dahisar.html', destination: '/locations/dahisar', permanent: true },
      { source: '/pest-control-service-diva.html', destination: '/locations/diva', permanent: true },
      { source: '/pest-control-service-dombivali.html', destination: '/locations/dombivali', permanent: true },
      { source: '/pest-control-service-ghansoli.html', destination: '/locations/ghansoli', permanent: true },
      { source: '/pest-control-service-ghatkopar.html', destination: '/locations/ghatkopar', permanent: true },
      { source: '/pest-control-service-goregaon.html', destination: '/locations/goregaon', permanent: true },
      { source: '/pest-control-service-govandi.html', destination: '/locations/govandi', permanent: true },
      { source: '/pest-control-service-grant-road.html', destination: '/locations/grant-road', permanent: true },
      { source: '/pest-control-service-jogeshwari.html', destination: '/locations/jogeshwari', permanent: true },
      { source: '/pest-control-service-kalva.html', destination: '/locations/kalva', permanent: true },
      { source: '/pest-control-service-kamothe.html', destination: '/locations/kamothe', permanent: true },
      { source: '/pest-control-service-kandivali.html', destination: '/locations/kandivali', permanent: true },
      { source: '/pest-control-service-kanjurmarg.html', destination: '/locations/kanjurmarg', permanent: true },
      { source: '/pest-control-service-khar-road.html', destination: '/locations/khar-road', permanent: true },
      { source: '/pest-control-service-kharghar.html', destination: '/locations/kharghar', permanent: true },
      { source: '/pest-control-service-kurla.html', destination: '/locations/kurla', permanent: true },
      { source: '/pest-control-service-lokhandwala.html', destination: '/locations/lokhandwala', permanent: true },
      { source: '/pest-control-service-lower-parel.html', destination: '/locations/lower-parel', permanent: true },
      { source: '/pest-control-service-mahalaxmi.html', destination: '/locations/mahalaxmi', permanent: true },
      { source: '/pest-control-service-mahim.html', destination: '/locations/mahim', permanent: true },
      { source: '/pest-control-service-malad.html', destination: '/locations/malad', permanent: true },
      { source: '/pest-control-service-mankhurd.html', destination: '/locations/mankhurd', permanent: true },
      { source: '/pest-control-service-marine-line.html', destination: '/locations/marine-line', permanent: true },
      { source: '/pest-control-service-matunga.html', destination: '/locations/matunga', permanent: true },
      { source: '/pest-control-service-mira-road.html', destination: '/locations/mira-road', permanent: true },
      { source: '/pest-control-service-mulund.html', destination: '/locations/mulund', permanent: true },
      { source: '/pest-control-service-mumbai-central.html', destination: '/locations/mumbai-central', permanent: true },
      { source: '/pest-control-service-mumbai-cst.html', destination: '/locations/mumbai-cst', permanent: true },
      { source: '/pest-control-service-nahur.html', destination: '/locations/nahur', permanent: true },
      { source: '/pest-control-service-naigaon.html', destination: '/locations/naigaon', permanent: true },
      { source: '/pest-control-service-nalasopara.html', destination: '/locations/nalasopara', permanent: true },
      { source: '/pest-control-service-navi-mumbai.html', destination: '/locations/navi-mumbai', permanent: true },
      { source: '/pest-control-service-neral.html', destination: '/locations/neral', permanent: true },
      { source: '/pest-control-service-nerul.html', destination: '/locations/nerul', permanent: true },
      { source: '/pest-control-service-parel.html', destination: '/locations/parel', permanent: true },
      { source: '/pest-control-service-powai.html', destination: '/locations/powai', permanent: true },
      { source: '/pest-control-service-prabhadevi.html', destination: '/locations/prabhadevi', permanent: true },
      { source: '/pest-control-service-rabale.html', destination: '/locations/rabale', permanent: true },
      { source: '/pest-control-service-ram-mandir.html', destination: '/locations/ram-mandir', permanent: true },
      { source: '/pest-control-service-sakinaka.html', destination: '/locations/sakinaka', permanent: true },
      { source: '/pest-control-service-santacruz.html', destination: '/locations/santacruz', permanent: true },
      { source: '/pest-control-service-sion.html', destination: '/locations/sion', permanent: true },
      { source: '/pest-control-service-thane.html', destination: '/locations/thane', permanent: true },
      { source: '/pest-control-service-titwala.html', destination: '/locations/titwala', permanent: true },
      { source: '/pest-control-service-trombe.html', destination: '/locations/trombe', permanent: true },
      { source: '/pest-control-service-turbhe.html', destination: '/locations/turbhe', permanent: true },
      { source: '/pest-control-service-ulwe.html', destination: '/locations/ulwe', permanent: true },
      { source: '/pest-control-service-wadala.html', destination: '/locations/wadala', permanent: true },
      { source: '/pest-control-service-vasai.html', destination: '/locations/vasai', permanent: true },
      { source: '/pest-control-service-vashi.html', destination: '/locations/vashi', permanent: true },
      { source: '/pest-control-service-vasind.html', destination: '/locations/vasind', permanent: true },
      { source: '/pest-control-service-versova.html', destination: '/locations/versova', permanent: true },
      { source: '/pest-control-service-vidya-vihar.html', destination: '/locations/vidya-vihar', permanent: true },
      { source: '/pest-control-service-vikhroli.html', destination: '/locations/vikhroli', permanent: true },
      { source: '/pest-control-service-vile-parle.html', destination: '/locations/vile-parle', permanent: true },
      { source: '/pest-control-service-virar.html', destination: '/locations/virar', permanent: true },
    ];
  },
};

export default nextConfig;
